"""add chapter_id to agent_chats

Revision ID: 109ec56eb53a
Revises: 6865b201ef1c
Create Date: 2026-08-03 11:14:37.457697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109ec56eb53a'
down_revision: Union[str, Sequence[str], None] = '6865b201ef1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_chats', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_agent_chats_chapter_id'), 'agent_chats', ['chapter_id'], unique=False)
    op.create_foreign_key(None, 'agent_chats', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_chats', type_='foreignkey')
    op.drop_index(op.f('ix_agent_chats_chapter_id'), table_name='agent_chats')
    op.drop_column('agent_chats', 'chapter_id')
    # ### end Alembic commands ###
