"""Add status to AgentChat

Revision ID: 5edf32c6bdff
Revises: c31f054864cf
Create Date: 2026-08-01 17:39:50.701306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edf32c6bdff'
down_revision: Union[str, Sequence[str], None] = 'c31f054864cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_chats', sa.Column('status', sa.String(), server_default='completed', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_chats', 'status')
    # ### end Alembic commands ###
