"""add reset otp fields

Revision ID: d0549965895f
Revises: 109ec56eb53a
Create Date: 2026-08-03 11:24:40.314703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0549965895f'
down_revision: Union[str, Sequence[str], None] = '109ec56eb53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires_at')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
